### ISSUE TITLE
Prevent image resize if it smaller than w and h

### ISSUE THREAD

**Issue by Kila14** [JamesHeinrich/phpThumb#88] opened 2017-09-19 15:44 UTC
Hello.
If image width and height values smaller than w and h values than image will stretch to w and h values.
It's bug, or it's a normal behavior? And how we can prevent this?

**Comment by JamesHeinrich** [comment] 2017-09-19 17:11
Normal behaviour is to proportionately resize larger images smaller to fit in a box of WxH.
Images smaller than WxH will not be enlarged to fit, they will be returned at their original size

If the "aoe" (Allow Output Enlargement) parameter is set then smaller images will be enlarged proportionately to fit inside the WxH box (but may not be exactly WxH if the aspect ratio of the source image does not match the aspect ratio of WxH).
http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x3

If the "far" (Force Aspect Ratio) parameter is set then the image will be stretched to fit exactly WxH, even if the target and source aspect ratios are different.
http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x22

If the "iar" (Ignore Aspect Ratio) parameter is set then the image will be resized proportionately to fit inside WxH box, and then padded with background color ("bg" parameter) to fit exactly WxH.
http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x22

If the "zc" (Zoom-Crop) parameter is set then the image will be resized proportionately to fit the smallest dimension inside WxH. If the target and source aspect ratios are different then the longer dimension will be cropped.
http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x23

**Comment by Kila14** [comment] 2017-09-19 18:32
JamesHeinrich, thank you for taking the time to help me! Your PHP thumbnail generator is really good.

So, there is 2 way for small images (smaller than WxH):
1) Fill in WxH box (with defferent options).
2) Return as is.
There will be bad picture quality at the first way. At the same time phpThumb will not work at all in the second way, because we get output img = input img. But how can we get this: if image is smaller than WxH then output image width = W, height = H and our small image position = center of image (with adding bg color)?
The best parameter for this is "far". But it stretches the image fit WxH every time even when image is very small :(

**Comment by JamesHeinrich** [comment] 2017-09-19 18:42
Using for example `img.jpg` = 100x75
`phpThumb.php?src=img.jpg&w=200&h=200` -- your thumbnail will be returned as 100x75
`phpThumb.php?src=img.jpg&w=200&h=200&aoe=1` -- your thumbnail will be returned as 200x150 but bad quality
`phpThumb.php?src=img.jpg&w=200&h=200&far=1` -- your thumbnail will be returned as 200x200 but bad quality and also distorted/stretched
`phpThumb.php?src=img.jpg&w=200&h=200&iar=1` -- your thumbnail will be returned as 200x200 with your 100x75 image centered in a white background (you can change the background color with the `bg` parameter and hex color, e.g. `bg=FF99CC`)

**Comment by Kila14** [comment] 2017-09-20 07:39
> phpThumb.php?src=img.jpg&w=200&h=200 -- your thumbnail will be returned as 100x75
phpThumb.php?src=img.jpg&w=200&h=200&aoe=1 -- your thumbnail will be returned as 200x150 but bad quality (enlarged to 200%)
phpThumb.php?src=img.jpg&w=200&h=200&zc=1 -- your thumbnail will be returned as 100x75 (Zoom-Crop is only useful when the source image is larger in both W and H than the box)
phpThumb.php?src=img.jpg&w=200&h=200&aoe=1&zc=1 -- your thumbnail will be returned as 200x200 but bad quality and cropped (enlarged to 267% and cropped left/right)
phpThumb.php?src=img.jpg&w=200&h=200&far=1 -- your thumbnail will be returned as 200x200 but bad quality and also distorted/stretched

All this methods are useless for small images((

> phpThumb.php?src=img.jpg&w=200&h=200&iar=1 -- your thumbnail will be returned as 200x200 with your 100x75 image centered in a white background (you can change the background color with the bg parameter and hex color, e.g. bg=FF99CC)

It's not that. Because 100x75 image will not be centered in 200x200 image, it's just will be stretched to 200x200. Your example: http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x22

**Comment by JamesHeinrich** [comment] 2017-09-20 12:49
No. Please note there are two example images at [demo 22](http://phpthumb.sourceforge.net/demo/demo/phpThumb.demo.demo.php#x22), "far" (centres original small image in background padding) and "iar" (stretches image to fill box).
Please look at the [first example](http://phpthumb.sourceforge.net/demo/phpThumb.php?src=images%2Floco.jpg&w=300&h=300&far=1&bg=CCCCCC&hash=ed18e183a9823136dbf2da715b509c44), you want to Force Aspect Ratio:
`phpThumb.php?src=img.jpg&w=200&h=200&far=1`

**Comment by Kila14** [comment] 2017-09-20 14:46
JamesHeinrich, sory for my misunderstanding.
To do this:
![dtydyjydjy](https://user-images.githubusercontent.com/19303244/30650434-87fe4e32-9e2b-11e7-93ae-10420291679a.jpg)
I need use this: phpThumb.php?src=img.jpg&w=200&h=200&far=1  ?

**Comment by JamesHeinrich** [comment] 2017-09-20 16:25
Yes. Except it should probably be `phpThumb.php?src=img.jpg&w=200&h=200&far=1&bg=000000` if you want a black background.

**Comment by Kila14** [comment] 2017-09-20 18:40
I use MODX 2.5.8
And there is phpThumb 1.7.14-201608101311
I wrote a snippet to display the resulting pictures.

```
<?php
if (!isset($modx)) {
	define('MODX_API_MODE', true);

	$modx->getService('error','error.modError');
	$modx->setLogLevel(modX::LOG_LEVEL_ERROR);
	$modx->setLogTarget('FILE');
}

$dst = MODX_BASE_PATH.'img_thumb_small.jpg';

$params = array(
	'w' => 300,
	'h' => 300,
	'bg' => '000000',
	'q' => 90,
	'far' => '1'
);

$phpThumb = $modx->getService('modphpthumb','modPhpThumb', MODX_CORE_PATH . 'model/phpthumb/', array());
$phpThumb->setSourceFilename($src);
foreach ($params as $k => $v) {
	$phpThumb->setParameter($k, $v);
}

if ($phpThumb->GenerateThumbnail()) {
	if (!$phpThumb->renderToFile($dst)) {
		$modx->log(modX::LOG_LEVEL_ERROR, 'Could not save rendered image to'.$dst);
	}
}
else {
	$modx->log(modX::LOG_LEVEL_ERROR, print_r($phpThumb->debugmessages, 1));
}
```

This is result: https://beauty-shtuchki.ru/phpthumb
The second image stretched to 300x300 box.

**Comment by Kila14** [comment] 2017-09-20 19:27
Added original images before output images.

**Comment by JamesHeinrich** [comment] 2017-09-20 19:53
You might want to cycle through the debug log to see exactly what's happening.
```
foreach ($this->debugmessages as $debugstring) {
	echo $debugstring.'<br>';
}
```
(warning, it will output a _lot_ of information...)

**Comment by Kila14** [comment] 2017-09-20 20:10
Did it.

**Comment by JamesHeinrich** [comment] 2017-09-20 20:15
The debug messages you have are for the [large image](https://beauty-shtuchki.ru/assets/images/products/33/1.jpg), not the small one.

**Comment by Kila14** [comment] 2017-09-20 20:25
Sorry. Fixed.

**Comment by JamesHeinrich** [comment] 2017-09-20 21:27
It's a bit hard to trace through because you're using an old version and the line numbers don't match up.
Any chance you can update to the [lastest version of phpThumb](https://github.com/JamesHeinrich/phpThumb/archive/master.zip) (v1.7.15-201704271708) please?

**Comment by Kila14** [comment] 2017-09-20 22:16
Yes of course. I'll update phpThumb and i'll message the result here.
JamesHeinrich, thank you very much for your help me!

**Comment by Kila14** [comment] 2017-09-21 10:50
I did it.
But it still the same as was. May be it's because i replaced not all files.
The following have been replaced:
![tkrkydtkytdk](https://user-images.githubusercontent.com/19303244/30692229-47ae98e8-9ed3-11e7-8a4c-b50cc9128d2e.PNG)

header('Location: ./demo/'); was replaced on header('Location: /'); in index.php
phpThumb.config.php.default was renamed to phpThumb.config.php

**Comment by JamesHeinrich** [comment] 2017-09-21 13:46
It turns out there was some missing code -- it would behave as intended if ImageMagick was _not_available, but if ImageMagick was available it would incorrectly stretch the image.
Please try updating to the latest version again (1.7.15-201709210936), should only be phpthumb.class.php that changed.
Fixed in https://github.com/JamesHeinrich/phpThumb/commit/bf1d1d021dbce34c4bacb00bca44f402f4cbf1b0

**Closed by JamesHeinrich** 2017-09-21 13:46 UTC

**Comment by Kila14** [comment] 2017-09-21 14:03
It works correctly with updated phpthumb.class.php!
Thank you very much, James!!!
You are a excellent specialist.

**Comment by JamesHeinrich** [comment] 2017-09-21 19:40
Thanks for reporting the bug and your patience in testing it.
